### ISSUE TITLE
Bad traceback

### ISSUE THREAD

**Issue by Blissbill** [rabuchaim/geoip2fast#10]
Hi
I am using your package in my django project. When importing `from geoip2fast import GeoIP2Fast` you set [sys.tracebacklimit = 0](https://github.com/rabuchaim/geoip2fast/blob/main/geoip2fast/geoip2fast.py#L101), which causes errors in some djnago calls. For example, the debug page stops displaying. This causes discomfort. Could you please fix it? I'm using a temporary solution of `sys.tracebacklimit = None` after importing your package, but it seems too dirty.

**Comment by rabuchaim** [comment]
Hi Blissbill!

Thank you for your comment.. I will remove this line from the next versions, it is unnecessary.

**Comment by Blissbill** [comment]
Thanks for the quick response
Can you tell me when to expect the next version?

**Comment by rabuchaim** [comment]
Well... maybe this week. Last week I added some new things to the code and I'm going to remove this line and test everything properly.

I was working on a new file structure (https://github.com/rabuchaim/geoip2fast/issues/8) that takes up much less memory, but I lost all the code... I had my laptops and backup hard drives stolen, I had I had to rewrite a lot of codes for my work and I was quite busy and didn't update GeoIP2Fast as I would have liked.

There are new things that I want to launch in the next few days... I also made a version that accepts MMDB files and I'm thinking about how to launch... maybe a "GeoIP2Fast for MMDB". And I also made the GeoIP2Fast Server that accepts dat.gz and any MMDB file (displays latitude and longitude). It was really cool, fast and very stable (0.0001 + Network Latency), with rate limit, DoS protection, and completely customizable. I'm testing it thoroughly to be able to release it. Here's a preview of it.

![01-abuchaim-2024-06-05 15_11_10](https://github.com/rabuchaim/geoip2fast/assets/43393040/5167bd69-cfbb-4fc3-b45b-991c8d162adf)

![02-abuchaim-2024-06-05 15_29_46](https://github.com/rabuchaim/geoip2fast/assets/43393040/5dc28f03-e518-47fb-a2e5-51df6ee61fa7)

![03-abuchaim-2024-06-05 15_20_56](https://github.com/rabuchaim/geoip2fast/assets/43393040/eeca38d9-2e80-4a74-b1eb-35a76b9fb188)

![04-abuchaim-2024-06-05 15_24_15](https://github.com/rabuchaim/geoip2fast/assets/43393040/832a0b05-c41e-4cb2-91b7-579c1194a204)

**Comment by Blissbill** [comment]
It's really sad that stuff was stolen. Your work looks really cool. Looking forward to the next release.

**Comment by rabuchaim** [comment]
@Blissbill 

Sorry for the delay, the new version is now available with the removal of the sys.tracebacklimit line.

https://pypi.org/project/geoip2fast/1.2.2/

Please let me know if there are any problems.

-- Ricardo

**Comment by rabuchaim** [comment]
Closed
